pl.lodz.p.ftims.edu.pai.web/Controllers/TimesheetController.cs
using Microsoft.AspNet.Identity.Owin;
using pl.lodz.p.ftims.edu.pai.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pl.lodz.p.ftims.edu.pai.web.Controllers
{
    public class TimesheetController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        public TimesheetController()
        {

        }
        public TimesheetController(ApplicationRoleManager roleManager, ApplicationUserManager userManager)
        {
            _userManager = UserManager;
            _roleManager = RoleManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: Timesheet
        [Authorize(Roles = "EMPLOYEE")]
        public async System.Threading.Tasks.Task<ActionResult> Index()
        {
            var currentUser = await UserManager.FindByNameAsync(User.Identity.Name);

            TimesheetService.ManagementClient client = new TimesheetService.ManagementClient();
            TimesheetService.Timesheet[] timesheets = client.GetEmployeeTimesheetsForPeriod(currentUser.ApiId.ToString(), string.Empty, string.Empty);
            var model = timesheets.Select(t => new TimesheetListItemViewModel() { Id = t.Id, EndPeriod = t.EndDay, StartPeriod = t.StartDay, Status = t.Status });


            return View(model);
        }
        [Authorize(Roles = "MANAGER")]
        public async System.Threading.Tasks.Task<ActionResult> Review()
        {
            var currentUser = await UserManager.FindByNameAsync(User.Identity.Name);

            TimesheetService.ManagementClient client = new TimesheetService.ManagementClient();
            TimesheetService.Timesheet[] timesheets = client.GetTimesheetsNeedAction(currentUser.ApiId.ToString(), 0, 0);
            var model = timesheets.Select(t => new TimesheetListItemViewModel() { Id = t.Id, EndPeriod = t.EndDay, StartPeriod = t.StartDay, Status = t.Status });


            return View(model);
        }

        [Authorize(Roles = "EMPLOYEE")]
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Step1()
        {
            CreateTimesheetStep1ViewModel model = new CreateTimesheetStep1ViewModel();
            var today = DateTime.Now;
            switch (today.DayOfWeek)
            {
                case DayOfWeek.Tuesday:
                    model.StartPeriod = today.AddDays(6);
                    break;
                case DayOfWeek.Wednesday:
                    model.StartPeriod = today.AddDays(5);
                    break;
                case DayOfWeek.Thursday:
                    model.StartPeriod = today.AddDays(4);
                    break;
                case DayOfWeek.Friday:
                    model.StartPeriod = today.AddDays(3);
                    break;
                case DayOfWeek.Saturday:
                    model.StartPeriod = today.AddDays(2);
                    break;
                case DayOfWeek.Sunday:
                    model.StartPeriod = today.AddDays(1);
                    break;
                case DayOfWeek.Monday:
                    model.StartPeriod = today;
                    break;

            }
            model.EndPeriod = model.StartPeriod.AddDays(6);
            var currentUser = await UserManager.FindByNameAsync(User.Identity.Name);
            model.Owner = currentUser.ApiId;
            return View(model);
        }
        [Authorize(Roles = "EMPLOYEE")]
        [HttpPost]
        public ActionResult Step2(CreateTimesheetStep1ViewModel model)
        {
            CreateTimesheetStep2ViewModel createModel = new CreateTimesheetStep2ViewModel();
            createModel.StartPeriod = model.StartPeriod;
            createModel.EndPeriod = model.EndPeriod;
            createModel.Owner = model.Owner;
            TimesheetEntry entry = CreateEmptyEntry(model.StartPeriod);
            createModel = fillWithDataFromService(createModel);
            createModel.Entries.Add(entry);
            return View(createModel);
        }

        private CreateTimesheetStep2ViewModel fillWithDataFromService(CreateTimesheetStep2ViewModel createModel)
        {
            TimesheetService.IManagement service = new TimesheetService.ManagementClient();
            createModel.Projects = service.GetProjects(0, 0).Select(t => new SelectListItem() { Text = t.Name + "-" + t.Code, Value = t.Id.ToString() });
            createModel.Tasks = service.GetTasks(0, 0).Select(t => new SelectListItem() { Text = t.Name + "-" + t.Code, Value = t.Id.ToString() });
            return createModel;
        }

        private TimesheetEntry CreateEmptyEntry(DateTime model)
        {
            var entry = new TimesheetEntry();
            entry.Date1 = model;
            entry.Date2 = model.AddDays(1);
            entry.Date3 = model.AddDays(2);
            entry.Date4 = model.AddDays(3);
            entry.Date5 = model.AddDays(4);
            entry.Date6 = model.AddDays(5);
            entry.Date7 = model.AddDays(6);
            return entry;
        }

        [Authorize(Roles = "EMPLOYEE")]
        [HttpPost]
        public ActionResult Submit(CreateTimesheetStep2ViewModel model)
        {
            if (model.AddRows.HasValue)
            {
                for (int i = 0; i < model.AddRows.Value; i++)
                {
                    model.Entries.Add(CreateEmptyEntry(model.StartPeriod));
                }
                model = fillWithDataFromService(model);
                model.AddRows = null;
                return View("Step2", model);
            }
            else
            {
                TimesheetService.IManagement service = new TimesheetService.ManagementClient();
                TimesheetService.CreateTimesheet timesheet = new TimesheetService.CreateTimesheet();
                timesheet.StartDay = model.StartPeriod;
                timesheet.EndDay = model.EndPeriod;
                timesheet.UserId = model.Owner;
                List<TimesheetService.CreateEntry> list = new List<TimesheetService.CreateEntry>();
                foreach (var entry in model.Entries)
                {
                    TimesheetService.CreateEntry tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date1;
                    tmp.Hours = entry.Day1;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                    tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date2;
                    tmp.Hours = entry.Day2;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                    tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date3;
                    tmp.Hours = entry.Day3;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                    tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date4;
                    tmp.Hours = entry.Day4;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                    tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date5;
                    tmp.Hours = entry.Day5;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                    tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date6;
                    tmp.Hours = entry.Day6;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                    tmp = new TimesheetService.CreateEntry();
                    tmp.Date = entry.Date7;
                    tmp.Hours = entry.Day7;
                    tmp.ProjectId = int.Parse(entry.Project);
                    tmp.TaskId = int.Parse(entry.Task);
                    list.Add(tmp);
                }
                timesheet.Entries = list.ToArray();
                service.CreateTimesheet(timesheet);
                return RedirectToAction("Index");
            }
        }

        public async System.Threading.Tasks.Task<ActionResult> Decline(int id)
        {
            TimesheetService.IManagement service = new TimesheetService.ManagementClient();
            var currentUser = await UserManager.FindByNameAsync(User.Identity.Name);
            service.RejectTimesheet(id.ToString(), currentUser.ApiId.ToString());
            return RedirectToAction("Review");
        }
        public async System.Threading.Tasks.Task<ActionResult> Accept(int id)
        {
            TimesheetService.IManagement service = new TimesheetService.ManagementClient();
            var currentUser = await UserManager.FindByNameAsync(User.Identity.Name);
            service.AcceptTimesheet(id.ToString(), currentUser.ApiId.ToString());
            return RedirectToAction("Review");
        }

        public ActionResult View(int id)
        {

pl.lodz.p.ftims.edu.pai.web/Views/Timesheet/Index.cshtml
@model IEnumerable<pl.lodz.p.ftims.edu.pai.web.Models.TimesheetListItemViewModel>

@{
    ViewBag.Title = "Przegląd kart";
}

<h2>Moje karty czasu pracy</h2>

<p>
    @Html.ActionLink("Dodaj", "Step1", new { }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartPeriod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndPeriod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartPeriod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndPeriod)
            </td>
            <td>
                @if (item.Status == 0)
                {
                    <span class="label label-info">
                        Wysłany
                    </span>
                }
                @if (item.Status == 1)
                {
                    <span class="label label-success">
                        Zaakceptowany
                    </span>
                }
                @if (item.Status == 3)
                {
                    <span class="label label-danger">Odrzucony</span>
                }


            </td>
            <td>
                <div class="btn-group btn-group-sm" role="group">
                    @Html.ActionLink("Podgląd", "View", new { id = item.Id }, new { @class = "btn btn-default" })
                </div>
            </td>
        </tr>
    }

</table>

pl.lodz.p.ftims.edu.pai.web/Views/Timesheet/Review.cshtml
@model IEnumerable<pl.lodz.p.ftims.edu.pai.web.Models.TimesheetListItemViewModel>

@{
    ViewBag.Title = "Ocena kart";
}

<h2>Karty do przeglądu</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartPeriod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndPeriod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartPeriod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndPeriod)
            </td>
            <td>
                @if (item.Status == 0)
                {
                    <span class="label label-info">
                        Wysłany
                    </span>
                }
                @if (item.Status == 1)
                {
                    <span class="label label-success">
                        Zaakceptowany
                    </span>
                }
                @if (item.Status == 3)
                {
                    <span class="label label-danger">Odrzucony</span>
                }
            </td>
            <td>
                <div class="btn-group btn-group-sm" role="group">
                    @Html.ActionLink("Podgląd", "View", new { id = item.Id }, new { @class = "btn btn-default" })
                </div>
            </td>
        </tr>
    }

</table>

pl.lodz.p.ftims.edu.pai.web/Views/Timesheet/Step1.cshtml
@model pl.lodz.p.ftims.edu.pai.web.Models.CreateTimesheetStep1ViewModel

@{
    ViewBag.Title = "Krok 1";
}

<h2>Dodawanie karty</h2>


@using (Html.BeginForm("Step2","Timesheet",FormMethod.Post, new { @class=""}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Krok 1 </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartPeriod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartPeriod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartPeriod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndPeriod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndPeriod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndPeriod, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dalej" class="btn btn-primary" />
                @Html.ActionLink("Anuluj", "Index", new { }, new { @class = "btn btn-link" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pl.lodz.p.ftims.edu.pai.web/Views/Timesheet/Step2.cshtml
@model pl.lodz.p.ftims.edu.pai.web.Models.CreateTimesheetStep2ViewModel

@{
    ViewBag.Title = "Krok 2";
}

<h2>dodawanie karty</h2>


@using (Html.BeginForm("Submit", "Timesheet", FormMethod.Post,new { @class="timesheet-form"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Krok 2</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartPeriod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartPeriod, new { htmlAttributes = new { @class = "form-control date-input", @readonly = true } })
                @Html.ValidationMessageFor(model => model.StartPeriod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndPeriod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndPeriod, new { htmlAttributes = new { @class = "form-control date-input", @readonly = true } })
                @Html.ValidationMessageFor(model => model.EndPeriod, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })
        <div class="form-group">
            <div class="row row-header">
                <div class="col-md-3">Projekt</div>
                <div class="col-md-2">Zadanie</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date1)</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date2)</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date3)</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date4)</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date5)</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date6)</div>
                <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date7)</div>
            </div>
            @for (int i = 0; i < Model.Entries.Count; i++)
            {

                <div class="row">
                    <div class="col-md-3">
                        @Html.DropDownListFor(m => m.Entries[i].Project, Model.Projects)
                    </div>
                    <div class="col-md-2">
                        @Html.DropDownListFor(m => m.Entries[i].Task, Model.Tasks)
                    </div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day1)@Html.HiddenFor(m => m.Entries[i].Date1)</div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day2)@Html.HiddenFor(m => m.Entries[i].Date2)</div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day3)@Html.HiddenFor(m => m.Entries[i].Date3)</div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day4)@Html.HiddenFor(m => m.Entries[i].Date4)</div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day5)@Html.HiddenFor(m => m.Entries[i].Date5)</div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day6)@Html.HiddenFor(m => m.Entries[i].Date6)</div>
                    <div class="col-md-1">@Html.EditorFor(m => m.Entries[i].Day7)@Html.HiddenFor(m => m.Entries[i].Date7)</div>
                </div>
            }
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dalej" class="btn btn-primary" />
                @Html.ActionLink("Anuluj", "Index",new { },new { @class="btn btn-link"})
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

pl.lodz.p.ftims.edu.pai.web/Views/Timesheet/View.cshtml
@model pl.lodz.p.ftims.edu.pai.web.Models.TimesheetViewModel

@{
    ViewBag.Title = "Karta";
}


<div>
    <h4>Karta czasu pracy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartPeriod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartPeriod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndPeriod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndPeriod)
        </dd>

    </dl>
</div>
<div class="row" style="font-size:0.9em; font-weight:bold;background: #e6e6e6; ">
    <div class="col-md-3">Projekt</div>
    <div class="col-md-2">Zadanie</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date1)</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date2)</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date3)</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date4)</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date5)</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date6)</div>
    <div class="col-md-1">@Html.DisplayFor(m => m.Entries[0].Date7)</div>
</div>
@for (int i = 0; i < Model.Entries.Count; i++)
            {

    <div class="row">
        <div class="col-md-3">
            @Html.DisplayFor(m => m.Entries[i].Project)
        </div>
        <div class="col-md-2">
            @Html.DisplayFor(m => m.Entries[i].Task)
        </div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day1)</div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day2)</div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day3)</div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day4)</div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day5)</div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day6)</div>
        <div class="col-md-1">@Html.DisplayFor(m => m.Entries[i].Day7)</div>
    </div>
}
<h4>Historia</h4>

@for(int i = 0; i < Model.History.Count; i++)
{
    <div class="row">
        <div class="col-md-3">@Html.DisplayFor(m=>m.History[i].Date)</div>
        <div class="col-md-4">@Html.DisplayFor(m => m.History[i].UserName)</div>
        <div class="col-md-1">
            @if (Model.History[i].NewStatus == 0)
                {
                <span class="label label-info">
                    Wysłany
                </span>
            }
            @if (Model.History[i].NewStatus == 1)
                {
                <span class="label label-success">
                    Zaakceptowany
                </span>
            }
            @if (Model.History[i].NewStatus == 3)
                {
                <span class="label label-danger">Odrzucony</span>
            }
        </div>
    </div>
}




<p>
    @if (User.IsInRole("MANAGER"))
    {
        <div class="btn-group">
            @Html.ActionLink("Akceptuj", "Accept", new { id = Model.Id }, new { @class = "btn btn-success" })
            @Html.ActionLink("Odrzuć", "Decline", new { id = Model.Id }, new { @class = "btn btn-danger" })
        </div>
    }

    @Html.ActionLink("Powrót", "Index")
</p>